### ISSUE TITLE
Constructing contiguity spatial weights using from_dataframe and from_shapefile could give different results

### ISSUE THREAD

**Issue by weikang9009** [pysal/libpysal#212]
Constructing contiguity spatial weights using `from_dataframe` and `from_shapefile` could give different results. An example notebook with the Baltimore example data set is given [here](https://github.com/weikang9009/libpysal/blob/weight/notebooks/weight_issue.ipynb).

Based on the Baltimore example data set, constructing a Queen or Rook contiguity weight directly from the shapefile will give a (210,210) weight matrix (with `from_shapefile`), while constructing that from the GeoDataFrame will produce a (211,211) weight matrix (with `from_shapefile`).

In contrast, KNN constructor gives identical spatial weight matrices (both are (211,211)).

**Comment by ljwolf** [comment]
Thanks! Can replicate and fix :)

[Here](https://github.com/pysal/libpysal/blob/master/libpysal/weights/contiguity.py#L45), we build a backup iterator for shapes because I need to check the geometry type. If it's a point, I want to build a voronoi frame. If it's polygons, I want to build a straight contiguity graph. We're doing this using *iterators( rather than lists because an earlier design goal for these weights constructors was to preserve the original laziness of the `libpysal.io.FileIO` readers: we should be lazy about the content of that `polygons` argument, in case they've gotta be read from the disk. 

So, when we pass that copied iterator to [`get_points_array`](https://github.com/pysal/libpysal/blob/master/libpysal/weights/contiguity.py#L48), we use the [try/except pattern](https://github.com/pysal/libpysal/blob/master/libpysal/weights/util.py#L1027) there:
```python
    try:
        data = np.vstack([np.array(shape.centroid) for shape in iterable])
    except AttributeError:
        data = np.vstack([shape for shape in iterable])
    return data
```
This works just fine *if and only if* the iterable is eager. 

But, if the iterable is *lazy* (like, a generator or something from `iter()`), this:
1. gets a `shape`. Since the iterable is new, this is the first shape. 
2. tries & fails to access its centroid
3. gets a `shape`. Since the iterable has already been started in step 1, this is now the second shape

You can see for yourself 
```python
iterable = (item in (1,2,3,4,5)) # build yourself a generator
try:
    result = [a.cant_touch_this for a in iterable]
except AttributeError:
    result = [a for a in iterable]
```
`result` will have `[2,3,4,5]`. 

So, I think the appropriate fix is to force the input to a list in `get_points_array()`, since it's eager and must return an array.

**Comment by ljwolf** [comment]
Or, I guess, to keep with earlier design concerns, we could [use the same iterable copying strategy as before](https://docs.python.org/3/library/itertools.html#itertools.tee)
