### ISSUE TITLE
BUG: weights.W.asymmetry does not support custom ids

### ISSUE THREAD

**Issue by martinfleis** [pysal/libpysal#540]
```py
>>> neighbors={"a":["b","c","d"], "b":["b","c","d"], "c":["a","b"], "d":["a","b"]}
>>> weights_d={"a":[1,1,1], "b":[1,1,1], "c":[1,1], "d":[1,1]}
>>> w=weights.W(neighbors,weights_d)
>>> w.asymmetry()
[(0, 1), (1, 0)]
```

This should be a ``list`` of ``(i,j)`` tuples, as per docstring but it is capturing integer ids coming from sparse.

It should be this:

```
[("a", "b"), ("b", "a")]
```

**Comment by jGaboardi** [comment]
Locally I've added the following to after [line 1280](https://github.com/pysal/libpysal/blob/e743c48c8bd3b74b423202ef5bb9b7316e9ac14e/libpysal/weights/weights.py#L1280):

```python
if isinstance(self.id_order[0], str):
    id_order_array = np.asarray(self.id_order)
    ids = tuple(id_order_array[ids[i]] for i in (0, 1))
```

This returns the correct ID labels if the labels are strings. Another thing we may consider though is if IDs are not strings, but numeric values that are not a 0-indexed range...

**Comment by jGaboardi** [comment]
Tests pass locally when simply leaving out the conditional:

```python
id_order_array = np.asarray(self.id_order)
ids = np.nonzero(wd)
ids = tuple(id_order_array[ids[i]] for i in (0, 1))
```

**Comment by martinfleis** [comment]
> Another thing we may consider though is if IDs are not strings, but numeric values that are not a 0-indexed range...

That is another valid case we should support. This one can be especially confusing. Your W is indexed by int, you get back int but it refers to position, not the value.

**Comment by jGaboardi** [comment]
2 more complications with indices that are not both (a) monotonically increasing integers and (b) 0-based:

* With the above array-based solution, if there are mixed-numeric types all values will be coerced to floats. This is probably a super edge case, but it exists nonetheless.
* The sorting that is happening in line [L1285](https://github.com/pysal/libpysal/blob/e743c48c8bd3b74b423202ef5bb9b7316e9ac14e/libpysal/weights/weights.py#L1285) may not give the intended result (and does the even matter?)

**Comment by jGaboardi** [comment]
Perhaps simply adding an `i2id` property (an inverse of [`id2i`](https://github.com/pysal/libpysal/blob/e743c48c8bd3b74b423202ef5bb9b7316e9ac14e/libpysal/weights/weights.py#L615)) and use that to translate the [`ijs`](https://github.com/pysal/libpysal/blob/e743c48c8bd3b74b423202ef5bb9b7316e9ac14e/libpysal/weights/weights.py#L1284) object would be a prudent solution.

**Comment by martinfleis** [comment]
Or just inverting `id2i` on the fly?

**Comment by jGaboardi** [comment]
This was my first thought, and absolutely the most simple solution. Actually doing the on-the-fly translation *after* the sorting on [L1285](https://github.com/pysal/libpysal/blob/e743c48c8bd3b74b423202ef5bb9b7316e9ac14e/libpysal/weights/weights.py#L1285) along with setting the [`id_order`](https://github.com/pysal/libpysal/blob/e743c48c8bd3b74b423202ef5bb9b7316e9ac14e/libpysal/weights/weights.py#L89) upon instantiation seems to resolve the issues I listed above *and* allows for mixed string-numeric dtype indices.

Two more things to think about:
* Are we sure, at the moment at least, that there would be no other use for being able to create and cache an `i2id` object in the current `weights` structure?
* Since the on-the-fly translation is [already happening](https://github.com/pysal/libpysal/blob/c6d8e2a94a78d3f673735ac801fb896361184bbf/libpysal/graph/base.py#L802) in the ongoing `W` to `Graph` restructuring, perhaps we need to give further thought to the [sorting that happens there](https://github.com/pysal/libpysal/blob/c6d8e2a94a78d3f673735ac801fb896361184bbf/libpysal/graph/base.py#L811), too? (Along with supporting mixed types in indices? Or no?)

**Comment by martinfleis** [comment]
> Are we sure, at the moment at least, that there would be no other use for being able to create and cache an i2id object in the current weights structure?

I am not sure how much energy I want to give thinking about future of `W` to be fair.

> Since the on-the-fly translation is [already happening](https://github.com/pysal/libpysal/blob/c6d8e2a94a78d3f673735ac801fb896361184bbf/libpysal/graph/base.py#L802) in the ongoing W to Graph restructuring, perhaps we need to give further thought to the [sorting that happens there](https://github.com/pysal/libpysal/blob/c6d8e2a94a78d3f673735ac801fb896361184bbf/libpysal/graph/base.py#L811), too? (Along with supporting mixed types in indices? Or no?)

Does the sorting matter?

**Comment by jGaboardi** [comment]
> I am not sure how much energy I want to give thinking about future of W to be fair.

Same and agreed at this point

> Does the sorting matter?

I might say yes and no, especially for a custom ID case, like [non-monotonic integers](https://github.com/pysal/libpysal/pull/543/files#diff-4bdb798fafe76ef920408e89f1f7fb2b31b87994b09a5842511cff3cec6f92bbR137-R144), where the index may not only not be increasing, but also out of "order". However, so long as we are clear in the docstring that a sorting is happening (which it currently is not), I suppose it wouldn't matter.

**Comment by martinfleis** [comment]
So you just expect the output of `asymmetry` to be a subset of pairs in their original order, correct?

**Comment by jGaboardi** [comment]
As a user [reading the docstring](https://github.com/pysal/libpysal/blob/e743c48c8bd3b74b423202ef5bb9b7316e9ac14e/libpysal/weights/weights.py#L1248-L1250), I would not expect the returned `list` to sorted. And since the [`Example`](https://github.com/pysal/libpysal/blob/e743c48c8bd3b74b423202ef5bb9b7316e9ac14e/libpysal/weights/weights.py#L1261) uses a standard monotonic integer index, it can't be inferred from context alone. I think probably you are correct that it doesn't matter that sorting should happen, but it should be clear that it is happening. If you agree, I will update #540 (code, tests, and docstring).

Perhaps we should get other devs opinion on this? @knaaptime, @ljwolf, @sjsrey

**Comment by jGaboardi** [comment]
Following https://github.com/pysal/libpysal/issues/540#issuecomment-1668465908 I am going to add some clarifying language to the docstring. I will also add (appropriate) clarifying language to the docstring in the new `Graph` class.
