### ISSUE TITLE
2 considerations for `id2i` in the new `Graph` class

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#549]
xref: https://github.com/pysal/libpysal/pull/544#discussion_r1291561087

> * Regarding the public vs. private discussion for `id2i`, was this talked about anywhere else besides [here](https://github.com/pysal/libpysal/pull/542#issuecomment-1668456231)? Since `id2i` is currently exposed in the `W` implementation, I am curious what the argument is for making it private in the new `Graph` implementation.
> * Also, I wanted to bring up the idea again to discuss the potential usefulness of an `i2id` property (or `_i2id` if we stick with the current private schema). Currently that translated lookup is only used within [`asymmetry`](https://github.com/pysal/libpysal/blob/e579820a444ac70395e079b99601e636c6728ecc/libpysal/graph/base.py#L808), but I am wondering if anyone can think of other situations where it might be helpful? If we will be using a translated lookup anywhere else, then another property  is surely warranted IMHO. 
>   * xref: https://github.com/pysal/libpysal/issues/540#issuecomment-1667093292

**Comment by martinfleis** [comment]
> I am curious what the argument is for making it private in the new Graph implementation.

It feels more like an internal information than user should not need to interact with. When using `Graph` and its methods, it always returns proper index so custom mapping is not relevant for a user. When casting to sparse, a user may potentially be interested in it but I assume that in that case they still have the original data they used to create Graph in the first place, to which sparse is aligned. So there's no need for any mapping either because the original data they may want to link to sparse are aligned anyway. But I am happy to reconsider that. What I'd like to avoid is bloating of the API with methods that may be potentially useful in edge cases, but will in practice be used once over in spopt or somewhere. 

The last argument also applies to `i2id`. There may be internal cases where this is useful but an inversion of a dict using dict comprehension is extremely cheap operation so the performance benefit is marginal. If we find ourselves needing it in more places than a current one, I am happy to add it as another private property but I am not convinced of its need as of now.

**Comment by jGaboardi** [comment]
@martinfleis Both these explanations seem reasonable to me. I am happy to have this closed for the time being until it should be considered again. If any other devs have strong opinions either way, we can reopen.
